name: notepadnext
base: core24
version: 'v0.14'
summary: A cross-platform, reimplementation of Notepad++
description: |
  Notepad Next is yet another text and source code editor.

grade: stable
confinement: classic

contact: https://github.com/dail8859/NotepadNext
issues: https://github.com/dail8859/NotepadNext/issues
website: https://github.com/dail8859/NotepadNext
license: GPL-3.0

apps:
  notepadnext:
    command: usr/bin/NotepadNext
    common-id: com.github.dail8859.NotepadNext
    environment:
      LD_LIBRARY_PATH: "$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET:$LD_LIBRARY_PATH"
      LIBGL_DRIVERS_PATH: "$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/dri:$LIBGL_DRIVERS_PATH"
      DISABLE_WAYLAND: 1
      __EGL_VENDOR_LIBRARY_DIRS: "$SNAP/etc/glvnd/egl_vendor.d:$SNAP/usr/share/glvnd/egl_vendor.d"
      QT_PLUGIN_PATH: "$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/qt6/plugins"

assumes:
  - snapd2.55.3

parts:
  mesa-no-patchelf:
    after: []
    plugin: nil
    build-attributes:
      - no-patchelf
    build-packages: []
    stage-packages:
      - libgl1-mesa-dri
      - libglx-mesa0
    prime:
      - "-lib/udev"
      - "-usr/doc"
      - "-usr/doc-base"
      - "-usr/share/applications"
      - "-usr/share/apport"
      - "-usr/share/bug"
      - "-usr/share/doc"
      - "-usr/share/doc-base"
      - "-usr/share/icons"
      - "-usr/share/libdrm"
      - "-usr/share/libwacom"
      - "-usr/share/lintian"
      - "-usr/share/man"
      - "-usr/share/pkgconfig"
  notepadnext:
    after: [mesa-no-patchelf]
    plugin: nil
    source: https://github.com/dail8859/NotepadNext.git
    source-type: git
    source-tag: $SNAPCRAFT_PROJECT_VERSION
    build-attributes:
      - no-patchelf
    override-pull: |
      git clone --recurse-submodules --branch $SNAPCRAFT_PROJECT_VERSION \
        https://github.com/dail8859/NotepadNext.git
    override-build: |
      cd NotepadNext
      qmake6 src/NotepadNext.pro "DISTRIBUTION=Snap"
      make -j$(nproc)
      make install INSTALL_ROOT=$SNAPCRAFT_PART_INSTALL
    build-packages:
      - make
      - build-essential
      - qt6-base-dev
      - qt6-base-private-dev
      - qt6-tools-dev
      - qt6-tools-dev-tools
      - qmake6
      - pkg-config
      - qt6-5compat-dev
      - libxkbcommon-dev
      - libxcb-cursor-dev
      - libcups2-dev
    stage-packages:
      - libgl1
      - libglx0
      - libglvnd0
      - libqt6core6t64
      - libqt6gui6t64
      - libqt6network6t64
      - libqt6printsupport6t64
      - libqt6widgets6t64
      - libx11-6
      - libxau6
      - libxdmcp6
      - libdouble-conversion3
      - libgraphite2-3
      - libharfbuzz0b
      - libicu74
      - libmd4c0
      - libpcre2-16-0
      - libxcb1
      - qt6-wayland
      - qt6-qpa-plugins
      - libxcb-cursor0
      - libxkbcommon0
      - libxkbcommon-x11-0
      - libqt6core5compat6
    prime:
      - "-usr/lib/*/*mesa*"
      - "-usr/lib/*/dri"
