name: 🧪 Test snap can be built on x86_64 for Qt 6

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5'
          modules: 'qt5compat'
          cache: true
